### ISSUE TITLE
Issues running splits

### ISSUE THREAD

**Issue by Soren90** [cout/sm_room_timer#3]
Hi,

I really like this project. I do however have some issues with doing splits using the example split file:

```
(venv) ➜  sm_room_timer git:(master) ./sm_practice_timer.py -f test.csv --splits splits/any_percent_kpdr25.txt --usb2snes
Route is incomplete
Traceback (most recent call last):
  File "/home/soren/Stream/sm_room_timer/./sm_practice_timer.py", line 655, in <module>
    main()
    ~~~~^^
  File "/home/soren/Stream/sm_room_timer/./sm_practice_timer.py", line 595, in main
    split_segments = Splits.from_segment_and_split_names(
        args.segments,
        split_names,
        rooms,
        route)
  File "/home/soren/Stream/sm_room_timer/splits.py", line 56, in from_segment_and_split_names
    splits = [ transition_from_name(name, rooms, route) for name in split_names ]
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/soren/Stream/sm_room_timer/splits.py", line 23, in transition_from_name
    return route.find_nth_transition_by_room(room, n)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/soren/Stream/sm_room_timer/route.py", line 49, in find_nth_transition_by_room
    raise RuntimeError("Could not find %s in route: %s" % (room.name, route))
RuntimeError: Could not find Landing Site in route: 
(venv) ➜  sm_room_timer git:(master) python --version
Python 3.13.1
```

Are you supposed to have some data saved for thge splits to work? Or am I doing something wrong

**Comment by Soren90** [comment]
I just read the documentation again. I now understand that "defining a route" actually means doing a run to get data before defining splits.

Sorry for the unnecessary issue creation!
